### ISSUE TITLE
PHP 7.4 deprecation

### ISSUE THREAD

**Issue by mops1k** [snc/SncRedisBundle#549]
Hello, after upd. to 7.4 throw this deprecation:
```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/project/symfony/vendor/snc/redis-bundle/DependencyInjection/Configuration/RedisDsn.php on line 193
```

**Comment by B-Galati** [comment]
Hello @mops1k, Thank you for reporting!

Would you mind sending a PR?

**Comment by mops1k** [comment]
As i see, fixed in latest version

**Comment by mops1k** [comment]
PR #552

**Comment by B-Galati** [comment]
PR #552 merged

**Comment by beephotography** [comment]
@B-Galati why is this fix only available on the specific 2.1 branch? I still don't get the fix when I update to `"snc/redis-bundle": "2.1.12"` in composer.json.

**Comment by B-Galati** [comment]
@beephotography Not released yet for v2, master branch (v3) is already fixed. 

You can try to upgrade to v3 if you can. It should be pretty simple if you are using Symfony 3.4+.

**Comment by B-Galati** [comment]
Just released 2.1.13

**Comment by beephotography** [comment]
@B-Galati thank you very much :pray:
